apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secret
  labels:
    app: auth-service
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.global.postgres.password | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.global.keycloak.adminPassword | quote }}
  FRONT_CLIENT_SECRET: {{ .Values.global.frontClientSecret | quote }}
