apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts-service.fullname" . }}-config
  labels:
    app: accounts-service
data:
  ACCOUNTS_SERVICE_PORT: {{ .Values.containerPort | quote }}
  POSTGRES_HOST: {{ .Values.global.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.global.postgres.port | quote }}
  POSTGRES_DB: {{ .Values.global.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.global.postgres.user | quote }}
  KEYCLOAK_EXTERNAL_URL: {{ .Values.global.keycloak.externalUrl | quote }}
  KEYCLOAK_INTERNAL_URL: {{ .Values.global.keycloak.internalUrl | quote }}
  KEYCLOAK_REALM: {{ .Values.global.keycloak.realm | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.global.kafka.bootstrapServers | quote }}
