apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounts-service.fullname" . }}-secret
  labels:
    app: accounts-service
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.global.postgres.password | quote }}
