apiVersion: v2
name: bank-app
description: Bank microservices application
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: postgres
    version: "1.0.0"
    repository: "file://charts/postgres"
  - name: keycloak
    version: "1.0.0"
    repository: "file://charts/keycloak"
  - name: accounts-service
    version: "1.0.0"
    repository: "file://charts/accounts-service"
  - name: auth-service
    version: "1.0.0"
    repository: "file://charts/auth-service"
  - name: cash-service
    version: "1.0.0"
    repository: "file://charts/cash-service"
  - name: transfer-service
    version: "1.0.0"
    repository: "file://charts/transfer-service"
  - name: notifications-service
    version: "1.0.0"
    repository: "file://charts/notifications-service"
  - name: gateway-service
    version: "1.0.0"
    repository: "file://charts/gateway-service"
  - name: front-service
    version: "1.0.0"
    repository: "file://charts/front-service"
  - name: kafka
    version: "1.0.0"
    repository: "file://charts/kafka"
