global:
  postgres:
    host: postgres
    port: "5432"
    db: bankdb
    user: bankuser
    password: bankpass
  keycloak:
    internalUrl: "http://keycloak:9095"
    externalUrl: "http://localhost:9095"
    realm: bank-realm
    adminUser: admin
    adminPassword: admin
  microservicesClientSecret: microservices-secret-key-12345
  frontClientSecret: front-client-secret-key-67890
  gatewayClientSecret: gateway-client-secret-key-11111
  demoUserPassword: password
  kafka:
    bootstrapServers: "kafka:9092"
  services:
    accounts:
      host: "accounts-service"
      port: "8081"
    auth:
      host: "auth-service"
      port: "8083"
    cash:
      host: "cash-service"
      port: "8082"
    transfer:
      host: "transfer-service"
      port: "8085"
    gateway:
      host: "gateway-service"
      port: "8080"
    notifications:
      host: "notifications-service"
      port: "8086"

postgres:
  image: "postgres:16-alpine"
  storage: "1Gi"

keycloak:
  image: "quay.io/keycloak/keycloak:23.0"

accounts-service:
  image: "my-bank-app-accounts-service:latest"
  imagePullPolicy: IfNotPresent
  replicas: 1

auth-service:
  image: "my-bank-app-auth-service:latest"
  imagePullPolicy: IfNotPresent
  replicas: 1

cash-service:
  image: "my-bank-app-cash-service:latest"
  imagePullPolicy: IfNotPresent
  replicas: 1

transfer-service:
  image: "my-bank-app-transfer-service:latest"
  imagePullPolicy: IfNotPresent
  replicas: 1

notifications-service:
  image: "my-bank-app-notifications-service:latest"
  imagePullPolicy: IfNotPresent
  replicas: 1

gateway-service:
  image: "my-bank-app-gateway-service:latest"
  imagePullPolicy: IfNotPresent
  replicas: 1

front-service:
  image: "my-bank-app-front-service:latest"
  imagePullPolicy: IfNotPresent
  replicas: 1

kafka:
  image: "apache/kafka:3.9.0"
  storageSize: "1Gi"

zipkin:
  image: "openzipkin/zipkin:3"
  replicas: 1

prometheus:
  image: "prom/prometheus:v3.2.1"
  replicas: 1
  retention: "7d"

grafana:
  image: "grafana/grafana:11.4.0"
  replicas: 1
  adminUser: admin
  adminPassword: admin

elk:
  externalHost: host.docker.internal
