apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.global.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.global.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.postgres.password | quote }}
