apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front-service.fullname" . }}-config
  labels:
    app: front-service
data:
  FRONT_SERVICE_PORT: {{ .Values.containerPort | quote }}
  GATEWAY_SERVICE_HOST: {{ .Values.global.services.gateway.host | quote }}
  GATEWAY_PORT: {{ .Values.global.services.gateway.port | quote }}
  AUTH_SERVICE_HOST: {{ .Values.global.services.auth.host | quote }}
  AUTH_SERVICE_PORT: {{ .Values.global.services.auth.port | quote }}
  KEYCLOAK_EXTERNAL_URL: {{ .Values.global.keycloak.externalUrl | quote }}
  KEYCLOAK_INTERNAL_URL: {{ .Values.global.keycloak.internalUrl | quote }}
  KEYCLOAK_REALM: {{ .Values.global.keycloak.realm | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.global.kafka.bootstrapServers | quote }}
