apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-service
  labels:
    app: front-service
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: front-service
  template:
    metadata:
      labels:
        app: front-service
    spec:
      containers:
        - name: front-service
          image: {{ .Values.image | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy | default "Never" }}
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: {{ include "front-service.fullname" . }}-config
            - secretRef:
                name: {{ include "front-service.fullname" . }}-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 30
