apiVersion: v1
kind: Secret
metadata:
  name: {{ include "front-service.fullname" . }}-secret
  labels:
    app: front-service
type: Opaque
stringData:
  FRONT_CLIENT_SECRET: {{ .Values.global.frontClientSecret | quote }}
