
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.web=DEBUG
logging.level.org.springframework.security.oauth2.client=TRACE
logging.level.org.springframework.security.oauth2.client.oidc=TRACE

logging.level.ru.yandex.practicum=DEBUG

logging.level.org.springframework.web=DEBUG
