apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-secret
  labels:
    app: keycloak
type: Opaque
stringData:
  KC_DB_PASSWORD: {{ .Values.global.postgres.password | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.global.keycloak.adminPassword | quote }}
