apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-service.fullname" . }}-config
  labels:
    app: gateway-service
data:
  GATEWAY_PORT: {{ .Values.containerPort | quote }}
  AUTH_SERVICE_HOST: {{ .Values.global.services.auth.host | quote }}
  AUTH_SERVICE_PORT: {{ .Values.global.services.auth.port | quote }}
  ACCOUNTS_SERVICE_HOST: {{ .Values.global.services.accounts.host | quote }}
  ACCOUNTS_SERVICE_PORT: {{ .Values.global.services.accounts.port | quote }}
  CASH_SERVICE_HOST: {{ .Values.global.services.cash.host | quote }}
  CASH_SERVICE_PORT: {{ .Values.global.services.cash.port | quote }}
  TRANSFER_SERVICE_HOST: {{ .Values.global.services.transfer.host | quote }}
  TRANSFER_SERVICE_PORT: {{ .Values.global.services.transfer.port | quote }}
  KEYCLOAK_EXTERNAL_URL: {{ .Values.global.keycloak.externalUrl | quote }}
  KEYCLOAK_INTERNAL_URL: {{ .Values.global.keycloak.internalUrl | quote }}
  KEYCLOAK_REALM: {{ .Values.global.keycloak.realm | quote }}
