apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway-service.fullname" . }}-secret
  labels:
    app: gateway-service
type: Opaque
stringData:
  GATEWAY_CLIENT_SECRET: {{ .Values.global.gatewayClientSecret | quote }}
