apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer-service.fullname" . }}-config
  labels:
    app: transfer-service
data:
  TRANSFER_SERVICE_PORT: {{ .Values.containerPort | quote }}
  ACCOUNTS_SERVICE_HOST: {{ .Values.global.services.accounts.host | quote }}
  ACCOUNTS_SERVICE_PORT: {{ .Values.global.services.accounts.port | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.global.kafka.bootstrapServers | quote }}
  KEYCLOAK_EXTERNAL_URL: {{ .Values.global.keycloak.externalUrl | quote }}
  KEYCLOAK_INTERNAL_URL: {{ .Values.global.keycloak.internalUrl | quote }}
  KEYCLOAK_REALM: {{ .Values.global.keycloak.realm | quote }}
