apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transfer-service.fullname" . }}-secret
  labels:
    app: transfer-service
type: Opaque
stringData:
  MICROSERVICES_CLIENT_SECRET: {{ .Values.global.microservicesClientSecret | quote }}
