server.port=8081

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=TRACE

spring.r2dbc.url=r2dbc:postgresql://postgres:5432/bankdb
spring.r2dbc.username=bankuser
spring.r2dbc.password=${DB_PASSWORD}
spring.r2dbc.properties.schema=accounts_schema

spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=10

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/bank-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:9090/realms/bank-realm/protocol/openid-connect/certs

spring.security.oauth2.client.registration.keycloak.client-id=microservices-client
spring.security.oauth2.client.registration.keycloak.client-secret=${MICROSERVICES_CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email

spring.security.oauth2.client.provider.keycloak.token-uri=http://keycloak:9090/realms/bank-realm/protocol/openid-connect/token
