server.port=${AUTH_SERVICE_PORT:8083}

spring.r2dbc.url=r2dbc:postgresql://postgres:${POSTGRES_PORT:5432}/${POSTGRES_DB:bankdb}
spring.r2dbc.username=${POSTGRES_USER:bankuser}
spring.r2dbc.password=${DB_PASSWORD}
spring.r2dbc.properties.schema=auth_schema

spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=10

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_EXTERNAL_URL:http://localhost:9090}/realms/${KEYCLOAK_REALM:bank-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_INTERNAL_URL:http://keycloak:9090}/realms/${KEYCLOAK_REALM:bank-realm}/protocol/openid-connect/certs
