server.port=${GATEWAY_PORT:8080}

spring.cloud.gateway.discovery.locator.enabled=false

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true


spring.cloud.gateway.httpclient.connect-timeout=5000
spring.cloud.gateway.httpclient.response-timeout=10s

spring.cloud.gateway.httpclient.pool.type=elastic
spring.cloud.gateway.httpclient.pool.max-connections=500

spring.cloud.gateway.httpclient.compression=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_EXTERNAL_URL:http://localhost:9090}/realms/${KEYCLOAK_REALM:bank-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_INTERNAL_URL:http://keycloak:9090}/realms/${KEYCLOAK_REALM:bank-realm}/protocol/openid-connect/certs

spring.security.oauth2.client.provider.keycloak.token-uri=${KEYCLOAK_INTERNAL_URL:http://keycloak:9090}/realms/${KEYCLOAK_REALM:bank-realm}/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.authorization-uri=${KEYCLOAK_EXTERNAL_URL:http://localhost:9090}/realms/${KEYCLOAK_REALM:bank-realm}/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.user-info-uri=${KEYCLOAK_INTERNAL_URL:http://keycloak:9090}/realms/${KEYCLOAK_REALM:bank-realm}/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=${KEYCLOAK_INTERNAL_URL:http://keycloak:9090}/realms/${KEYCLOAK_REALM:bank-realm}/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

spring.security.oauth2.client.registration.keycloak.client-id=gateway-client
spring.security.oauth2.client.registration.keycloak.client-secret=${GATEWAY_CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.keycloak.scope=openid
