server.port=8086

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:9090/realms/bank-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:9090/realms/bank-realm/protocol/openid-connect/certs

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

logging.level.ru.yandex.practicum.notifications=DEBUG
logging.level.org.springframework.security=DEBUG
