server.port=${NOTIFICATIONS_SERVICE_PORT:8086}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_EXTERNAL_URL:http://localhost:9090}/realms/${KEYCLOAK_REALM:bank-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_INTERNAL_URL:http://keycloak:9090}/realms/${KEYCLOAK_REALM:bank-realm}/protocol/openid-connect/certs

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
