image: "bank-gateway-service:latest"
imagePullPolicy: Never
replicas: 1
global: {}
containerPort: 8080
service:
  type: LoadBalancer
  port: 8080
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
